### ISSUE TITLE
Training code and pretrained weights

### ISSUE THREAD

**Issue by anas-zafar** [laurabragagnolo/human3.6m-occluded#1]
Great work! Looking forward to the pretrained weights and training code to test it out. Thanks

**Comment by laurabragagnolo** [comment]
Hello Anas! Thank you for checking out our work!
This repo is meant for the generation of the Human3.6M-Occluded benchmark that we use in our [paper](https://www.arxiv.org/abs/2408.15810). You can already find all the related code.

For 3D pose estimation, we start off with an absolute human pose estimation algorithm ([Metrabs](https://istvansarandi.com/dozens/) in our experiments) and then we perform 3D joint fusion and reprojection-based optimization. Hence, for training code and weights please refer to [this repo](https://github.com/isarandi/metrabs).

I plan to make fusion and optimization code available soon :)
